apiVersion: apps/v1
kind: Deployment
metadata:
  name: tour-of-heroes-frontend
  namespace: heroes-app
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: tour-of-heroes:v1