apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: heroes-app
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - name: frontend-http
      port: 8081
      targetPort: 80
      protocol: TCP
